export const CHECKOUT_STAGE = "CHECKOUT_STAGE";

export const CHECKOUT_STAGE_DELIVERY = "CHECKOUT_STAGE_DELIVERY";
export const CHECKOUT_STAGE_CHECKOUT = "CHECKOUT_STAGE_CHECKOUT";
export const CHECKOUT_STAGE_PAYMENT = "CHECKOUT_STAGE_PAYMENT";
