export const ADD_TO_CART = "ADD_TO_CART";
export const GET_CART_LIST = "GET_CART_LIST";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const PLACE_ORDER = "PLACE_ORDER";
export const GET_REWARD_POINT_LIST = "GET_REWARD_POINT_LIST";
